server:
  port: 7777

spring:
  application:
    name: turbine


turbine:
  aggregator:
    clusterConfig: default
  appConfig: user,account
  clusterNameExpression: new String("default")


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/