server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/oceswang/spring-cloud.git
          searchPaths: micro-config-repo


eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/ 
      
management:
  context-path: /admin