server:
  port: 8001

spring:
  application:
    name: user
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/   